version: '3'

services: 
  backend:
    image: zerosoftwere/mps-backend
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_HOST=database
      - DB_NAME=mps
    links:
      - database
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mps